### ISSUE TITLE
WebUtils.SetUserLocale

### ISSUE THREAD

**Issue by davidhendrickmb** [RickStrahl/Westwind.AspNetCore#9]
Hi there,
Does the WebUtils.SetUserLocale function work with the Asp.Net Core version?
It works perfectly if I change my browser language, or if I add the culture= in the query string, but not if I specify the culture and UI culture (these are both strings). I'm trying to persist this using a simply cookie. 

`WebUtils.SetUserLocale(culture, culture, null, true, null, HttpContext);`

Thanks,
David

**Comment by moslem-hadi** [comment]
Hi. did you find any solution??

**Comment by davidhendrickmb** [comment]
I believe I just used the built in functions e.g. 
Thread.CurrentThread.CurrentCulture = new CultureInfo(request.CultureCode);
Thread.CurrentThread.CurrentUICulture = new CultureInfo(request.CultureCode);

**Comment by RickStrahl** [comment]
If I recall correctly this helper was removed since it couldn't generically auto-detect the browser language which was the main reason for this function.

**Comment by RickStrahl** [comment]
I added HttpContextExtensions.SetUserLocale which should now work as the old version did. The old version was dependent on HttpContext.Current to pick up the Accept-Languages - the new version explicitly requires the HttpContext/Request in order to do that so it seems best to add it as an extension method for HttpContext.

```cs
// uses browser locale from first language in Accept languages
HttpContext.SetUserLocale();

// specific locale
HttpContext.SetUserLocale("de-at");
```
